// <auto-generated />
using System;
using CodeFirst.EDM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirst.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20221012085653_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirst.EDM.tblcity", b =>
                {
                    b.Property<int>("city_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("city_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("city_id");

                    b.ToTable("tblcities");
                });

            modelBuilder.Entity("CodeFirst.EDM.tblemployee", b =>
                {
                    b.Property<int>("emp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("emp_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<int?>("city_id")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<DateTime?>("dob")
                        .HasColumnType("datetime2")
                        .HasColumnName("dob");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("f_name")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("f_name");

                    b.Property<decimal>("mobile")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("mobile");

                    b.Property<int>("salary")
                        .HasColumnType("int")
                        .HasColumnName("salary");

                    b.HasKey("emp_id");

                    b.ToTable("tblemployee");
                });
#pragma warning restore 612, 618
        }
    }
}
